# coding: utf-8

# flake8: noqa
"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from wave_ai_generated.models.agents_agent import AgentsAgent
from wave_ai_generated.models.agents_config import AgentsConfig
from wave_ai_generated.models.agents_list_response import AgentsListResponse
from wave_ai_generated.models.agents_tool import AgentsTool
from wave_ai_generated.models.agents_update_request import AgentsUpdateRequest
from wave_ai_generated.models.agents_version import AgentsVersion
from wave_ai_generated.models.agents_versions_response import AgentsVersionsResponse
from wave_ai_generated.models.apierr_envelope import ApierrEnvelope
from wave_ai_generated.models.apierr_envelope_er import ApierrEnvelopeEr
from wave_ai_generated.models.deployments_create_request import DeploymentsCreateRequest
from wave_ai_generated.models.deployments_deployment import DeploymentsDeployment
from wave_ai_generated.models.deployments_list_response import DeploymentsListResponse
from wave_ai_generated.models.deployments_pause_request import DeploymentsPauseRequest
from wave_ai_generated.models.deployments_run import DeploymentsRun
from wave_ai_generated.models.deployments_runs_response import DeploymentsRunsResponse
from wave_ai_generated.models.environments_create_request import EnvironmentsCreateRequest
from wave_ai_generated.models.environments_environment import EnvironmentsEnvironment
from wave_ai_generated.models.environments_list_response import EnvironmentsListResponse
from wave_ai_generated.models.execution_budget import ExecutionBudget
from wave_ai_generated.models.execution_create_session_request import ExecutionCreateSessionRequest
from wave_ai_generated.models.execution_event import ExecutionEvent
from wave_ai_generated.models.execution_events_response import ExecutionEventsResponse
from wave_ai_generated.models.execution_generation import ExecutionGeneration
from wave_ai_generated.models.execution_generations_response import ExecutionGenerationsResponse
from wave_ai_generated.models.execution_input import ExecutionInput
from wave_ai_generated.models.execution_inputs_response import ExecutionInputsResponse
from wave_ai_generated.models.execution_message import ExecutionMessage
from wave_ai_generated.models.execution_messages_response import ExecutionMessagesResponse
from wave_ai_generated.models.execution_reconcile_request import ExecutionReconcileRequest
from wave_ai_generated.models.execution_required_action import ExecutionRequiredAction
from wave_ai_generated.models.execution_required_actions_response import ExecutionRequiredActionsResponse
from wave_ai_generated.models.execution_session import ExecutionSession
from wave_ai_generated.models.execution_sessions_response import ExecutionSessionsResponse
from wave_ai_generated.models.execution_task import ExecutionTask
from wave_ai_generated.models.execution_task_request import ExecutionTaskRequest
from wave_ai_generated.models.execution_tasks_response import ExecutionTasksResponse
from wave_ai_generated.models.execution_text_request import ExecutionTextRequest
from wave_ai_generated.models.execution_tool_call import ExecutionToolCall
from wave_ai_generated.models.execution_tool_calls_response import ExecutionToolCallsResponse
from wave_ai_generated.models.execution_tool_result_request import ExecutionToolResultRequest
from wave_ai_generated.models.files_file import FilesFile
from wave_ai_generated.models.files_list_response import FilesListResponse
from wave_ai_generated.models.memory_conflict import MemoryConflict
from wave_ai_generated.models.memory_conflicts_response import MemoryConflictsResponse
from wave_ai_generated.models.memory_create_store_request import MemoryCreateStoreRequest
from wave_ai_generated.models.memory_delete_entry_request import MemoryDeleteEntryRequest
from wave_ai_generated.models.memory_entries_response import MemoryEntriesResponse
from wave_ai_generated.models.memory_entry import MemoryEntry
from wave_ai_generated.models.memory_list_response import MemoryListResponse
from wave_ai_generated.models.memory_revision import MemoryRevision
from wave_ai_generated.models.memory_revisions_response import MemoryRevisionsResponse
from wave_ai_generated.models.memory_store import MemoryStore
from wave_ai_generated.models.memory_write_entry_request import MemoryWriteEntryRequest
from wave_ai_generated.models.modelclient_func_call_spec import ModelclientFuncCallSpec
from wave_ai_generated.models.modelclient_tool_call import ModelclientToolCall
from wave_ai_generated.models.modelclient_usage import ModelclientUsage
from wave_ai_generated.models.skills_list_response import SkillsListResponse
from wave_ai_generated.models.skills_skill import SkillsSkill
from wave_ai_generated.models.vault_create_request import VaultCreateRequest
from wave_ai_generated.models.vault_credential import VaultCredential
from wave_ai_generated.models.vault_list_response import VaultListResponse

