# coding: utf-8

"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from wave_ai_generated.models.agents_acceptance_check import AgentsAcceptanceCheck
from wave_ai_generated.models.agents_tool import AgentsTool
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentsConfig(BaseModel):
    """
    AgentsConfig
    """ # noqa: E501
    acceptance: Optional[List[AgentsAcceptanceCheck]] = None
    delegation_policy: Optional[StrictStr] = None
    effort: Optional[StrictStr] = None
    expert_ids: Optional[List[StrictStr]] = None
    expert_versions: Optional[Dict[str, StrictInt]] = None
    instructions: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Answer clearly and cite your sources."]})
    model: StrictStr = Field(json_schema_extra={"examples": ["your-model-id"]})
    name: StrictStr = Field(json_schema_extra={"examples": ["Research assistant"]})
    skill_ids: Optional[List[StrictStr]] = None
    tools: Optional[List[AgentsTool]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["acceptance", "delegation_policy", "effort", "expert_ids", "expert_versions", "instructions", "model", "name", "skill_ids", "tools"]

    @field_validator('delegation_policy')
    def delegation_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['intersection', 'explicit']):
            raise ValueError("must be one of enum values ('intersection', 'explicit')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentsConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in acceptance (list)
        _items = []
        if self.acceptance:
            for _item_acceptance in self.acceptance:
                _items.append(_item_acceptance.to_dict() if _item_acceptance is not None else None)
            _dict['acceptance'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                _items.append(_item_tools.to_dict() if _item_tools is not None else None)
            _dict['tools'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if expert_ids (nullable) is None
        # and model_fields_set contains the field
        if self.expert_ids is None and "expert_ids" in self.model_fields_set:
            _dict['expert_ids'] = None

        # set to None if skill_ids (nullable) is None
        # and model_fields_set contains the field
        if self.skill_ids is None and "skill_ids" in self.model_fields_set:
            _dict['skill_ids'] = None

        # set to None if tools (nullable) is None
        # and model_fields_set contains the field
        if self.tools is None and "tools" in self.model_fields_set:
            _dict['tools'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentsConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acceptance": [AgentsAcceptanceCheck.from_dict(_item) for _item in obj["acceptance"]] if obj.get("acceptance") is not None else None,
            "delegation_policy": obj.get("delegation_policy"),
            "effort": obj.get("effort"),
            "expert_ids": obj.get("expert_ids"),
            "expert_versions": obj.get("expert_versions"),
            "instructions": obj.get("instructions"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "skill_ids": obj.get("skill_ids"),
            "tools": [AgentsTool.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


