# coding: utf-8

"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from wave_ai_generated.models.execution_budget import ExecutionBudget
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DeploymentsCreateRequest(BaseModel):
    """
    DeploymentsCreateRequest
    """ # noqa: E501
    agent_id: StrictStr
    agent_version: Optional[StrictInt] = None
    budget: Optional[ExecutionBudget] = None
    cron: Optional[StrictStr] = None
    environment_id: Optional[StrictStr] = None
    file_ids: Optional[List[StrictStr]] = None
    follow_latest: Optional[StrictBool] = None
    input: StrictStr
    memory_store_ids: Optional[List[StrictStr]] = None
    misfire_policy: Optional[StrictStr] = None
    name: StrictStr
    overlap_policy: Optional[StrictStr] = None
    timezone: Optional[StrictStr] = None
    vault_ids: Optional[List[StrictStr]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["agent_id", "agent_version", "budget", "cron", "environment_id", "file_ids", "follow_latest", "input", "memory_store_ids", "misfire_policy", "name", "overlap_policy", "timezone", "vault_ids"]

    @field_validator('misfire_policy')
    def misfire_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['skip', 'run_once']):
            raise ValueError("must be one of enum values ('skip', 'run_once')")
        return value

    @field_validator('overlap_policy')
    def overlap_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['skip', 'allow']):
            raise ValueError("must be one of enum values ('skip', 'allow')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeploymentsCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentsCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_id": obj.get("agent_id"),
            "agent_version": obj.get("agent_version"),
            "budget": ExecutionBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "cron": obj.get("cron"),
            "environment_id": obj.get("environment_id"),
            "file_ids": obj.get("file_ids"),
            "follow_latest": obj.get("follow_latest"),
            "input": obj.get("input"),
            "memory_store_ids": obj.get("memory_store_ids"),
            "misfire_policy": obj.get("misfire_policy"),
            "name": obj.get("name"),
            "overlap_policy": obj.get("overlap_policy"),
            "timezone": obj.get("timezone"),
            "vault_ids": obj.get("vault_ids")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


