# coding: utf-8

"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from wave_ai_generated.models.agents_agent import AgentsAgent
from wave_ai_generated.models.agents_config import AgentsConfig
from wave_ai_generated.models.execution_budget import ExecutionBudget
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExecutionTask(BaseModel):
    """
    ExecutionTask
    """ # noqa: E501
    agent: AgentsConfig
    agent_count: StrictInt
    agent_id: StrictStr
    agent_version: StrictInt
    attempts: StrictInt
    budget: ExecutionBudget
    cancel_requested: StrictBool
    created_at: datetime
    error: Optional[StrictStr] = None
    experts: Optional[Dict[str, AgentsAgent]] = None
    finished_at: Optional[datetime] = None
    id: StrictStr
    parent_id: Optional[StrictStr] = None
    result: Optional[StrictStr] = None
    root_id: StrictStr
    session_id: StrictStr
    started_at: Optional[datetime] = None
    state: StrictStr = Field(json_schema_extra={"examples": ["queued"]})
    tool_calls: StrictInt
    updated_at: datetime
    usage_known: StrictBool
    used_tokens: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["agent", "agent_count", "agent_id", "agent_version", "attempts", "budget", "cancel_requested", "created_at", "error", "experts", "finished_at", "id", "parent_id", "result", "root_id", "session_id", "started_at", "state", "tool_calls", "updated_at", "usage_known", "used_tokens"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['queued', 'running', 'waiting', 'unknown', 'succeeded', 'partial', 'failed', 'canceled']):
            raise ValueError("must be one of enum values ('queued', 'running', 'waiting', 'unknown', 'succeeded', 'partial', 'failed', 'canceled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent
        if self.agent:
            _dict['agent'] = self.agent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in experts (dict)
        _field_dict = {}
        if self.experts:
            for _key_experts in self.experts:
                _field_dict[_key_experts] = self.experts[_key_experts].to_dict() if self.experts[_key_experts] is not None else None
            _dict['experts'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent": AgentsConfig.from_dict(obj["agent"]) if obj.get("agent") is not None else None,
            "agent_count": obj.get("agent_count"),
            "agent_id": obj.get("agent_id"),
            "agent_version": obj.get("agent_version"),
            "attempts": obj.get("attempts"),
            "budget": ExecutionBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "cancel_requested": obj.get("cancel_requested"),
            "created_at": obj.get("created_at"),
            "error": obj.get("error"),
            "experts": dict(
                (_k, AgentsAgent.from_dict(_v))
                for _k, _v in obj["experts"].items()
            )
            if obj.get("experts") is not None
            else None,
            "finished_at": obj.get("finished_at"),
            "id": obj.get("id"),
            "parent_id": obj.get("parent_id"),
            "result": obj.get("result"),
            "root_id": obj.get("root_id"),
            "session_id": obj.get("session_id"),
            "started_at": obj.get("started_at"),
            "state": obj.get("state"),
            "tool_calls": obj.get("tool_calls"),
            "updated_at": obj.get("updated_at"),
            "usage_known": obj.get("usage_known"),
            "used_tokens": obj.get("used_tokens")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


