# coding: utf-8

"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExecutionTraceSummary(BaseModel):
    """
    ExecutionTraceSummary
    """ # noqa: E501
    cached_input_tokens: StrictInt
    failed_model_calls: StrictInt
    failed_tool_calls: StrictInt
    initial_queue_ms: Optional[Union[StrictFloat, StrictInt]]
    input_tokens: StrictInt
    model_calls: StrictInt
    model_ms: Union[StrictFloat, StrictInt]
    output_tokens: StrictInt
    phase_ms: Dict[str, Union[StrictFloat, StrictInt]]
    tool_calls: StrictInt
    tool_ms: Union[StrictFloat, StrictInt]
    unattributed_ms: Optional[Union[StrictFloat, StrictInt]]
    usage_known: StrictBool
    wall_ms: Optional[Union[StrictFloat, StrictInt]]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cached_input_tokens", "failed_model_calls", "failed_tool_calls", "initial_queue_ms", "input_tokens", "model_calls", "model_ms", "output_tokens", "phase_ms", "tool_calls", "tool_ms", "unattributed_ms", "usage_known", "wall_ms"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionTraceSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if initial_queue_ms (nullable) is None
        # and model_fields_set contains the field
        if self.initial_queue_ms is None and "initial_queue_ms" in self.model_fields_set:
            _dict['initial_queue_ms'] = None

        # set to None if unattributed_ms (nullable) is None
        # and model_fields_set contains the field
        if self.unattributed_ms is None and "unattributed_ms" in self.model_fields_set:
            _dict['unattributed_ms'] = None

        # set to None if wall_ms (nullable) is None
        # and model_fields_set contains the field
        if self.wall_ms is None and "wall_ms" in self.model_fields_set:
            _dict['wall_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionTraceSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cached_input_tokens": obj.get("cached_input_tokens"),
            "failed_model_calls": obj.get("failed_model_calls"),
            "failed_tool_calls": obj.get("failed_tool_calls"),
            "initial_queue_ms": obj.get("initial_queue_ms"),
            "input_tokens": obj.get("input_tokens"),
            "model_calls": obj.get("model_calls"),
            "model_ms": obj.get("model_ms"),
            "output_tokens": obj.get("output_tokens"),
            "phase_ms": obj.get("phase_ms"),
            "tool_calls": obj.get("tool_calls"),
            "tool_ms": obj.get("tool_ms"),
            "unattributed_ms": obj.get("unattributed_ms"),
            "usage_known": obj.get("usage_known"),
            "wall_ms": obj.get("wall_ms")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


