# coding: utf-8

"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from wave_ai_generated.models.modelclient_usage import ModelclientUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExecutionGeneration(BaseModel):
    """
    ExecutionGeneration
    """ # noqa: E501
    attempt: StrictInt
    duration_ms: Optional[StrictInt] = Field(description="Duration in milliseconds; null when unknown.")
    error: Optional[StrictStr] = None
    finished_at: Optional[datetime] = None
    first_delta_ms: Optional[StrictInt] = Field(description="First-delta latency in milliseconds; null if no delta has arrived or the value is unknown.")
    id: StrictStr
    message_id: Optional[StrictStr] = None
    model: StrictStr
    purpose: StrictStr
    started_at: datetime
    state: StrictStr
    task_id: StrictStr
    usage: ModelclientUsage
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attempt", "duration_ms", "error", "finished_at", "first_delta_ms", "id", "message_id", "model", "purpose", "started_at", "state", "task_id", "usage"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['running', 'completed', 'failed', 'interrupted']):
            raise ValueError("must be one of enum values ('running', 'completed', 'failed', 'interrupted')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionGeneration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if duration_ms (nullable) is None
        # and model_fields_set contains the field
        if self.duration_ms is None and "duration_ms" in self.model_fields_set:
            _dict['duration_ms'] = None

        # set to None if first_delta_ms (nullable) is None
        # and model_fields_set contains the field
        if self.first_delta_ms is None and "first_delta_ms" in self.model_fields_set:
            _dict['first_delta_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionGeneration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attempt": obj.get("attempt"),
            "duration_ms": obj.get("duration_ms"),
            "error": obj.get("error"),
            "finished_at": obj.get("finished_at"),
            "first_delta_ms": obj.get("first_delta_ms"),
            "id": obj.get("id"),
            "message_id": obj.get("message_id"),
            "model": obj.get("model"),
            "purpose": obj.get("purpose"),
            "started_at": obj.get("started_at"),
            "state": obj.get("state"),
            "task_id": obj.get("task_id"),
            "usage": ModelclientUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


