# coding: utf-8

"""
    Wave AI API

    Managed Agents service. All /v1 endpoints require a Bearer Wave API Key; issue it with `wave bootstrap`. Enter the raw Wave API Key in the SDK and Swagger UI bearer configuration. Offset pagination returns data and an optional next_offset (omitted on the last page); message history uses next_after, and event lists resume from the last sequence. JSON errors return {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"...\"},\"request_id\":\"req_...\"}. File-transfer Range errors return text/plain; conditional downloads and health checks may return empty responses. JSON requests reject unknown fields; non-multipart request bodies are limited to 2 MiB. Nullable fields use nullable; omission is not equivalent to null. Interactive documentation: /swagger/index.html. OpenAPI 3 spec: /swagger/openapi.json; legacy Swagger 2: /swagger/doc.json.  [English](/swagger/index.html?lang=en) · [中文](/swagger/index.html?lang=zh-CN)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelclientUsage(BaseModel):
    """
    ModelclientUsage
    """ # noqa: E501
    cache_read_input_tokens: Optional[StrictInt] = Field(description="Provider-reported cache-read token count; null when unknown.")
    completion_tokens: Optional[StrictInt] = Field(description="Provider-reported output token count; null when unknown.")
    prompt_tokens: Optional[StrictInt] = Field(description="Provider-reported input token count; null when unknown and must not be billed as zero.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cache_read_input_tokens", "completion_tokens", "prompt_tokens"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelclientUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if cache_read_input_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_read_input_tokens is None and "cache_read_input_tokens" in self.model_fields_set:
            _dict['cache_read_input_tokens'] = None

        # set to None if completion_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.completion_tokens is None and "completion_tokens" in self.model_fields_set:
            _dict['completion_tokens'] = None

        # set to None if prompt_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_tokens is None and "prompt_tokens" in self.model_fields_set:
            _dict['prompt_tokens'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelclientUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache_read_input_tokens": obj.get("cache_read_input_tokens"),
            "completion_tokens": obj.get("completion_tokens"),
            "prompt_tokens": obj.get("prompt_tokens")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


